### ISSUE TITLE
[Summary] advanced image operations

### ISSUE THREAD

**Issue by abnerlee** [typora/typora-issues#2242]
- [ ] Swipe Images #2220
- [x] Zoom Images #2220
- [x] Rename #2218 (supported by move image)
- [x] Open in external viewer #2200 (supported by open in Finder / Explorer)
- [ ] Resize #2189
- [ ] Change format #2459
- [x] Refresh images #2661
- [x] Remove Image #4016
- [ ] OCR in images #4133

Relate topic #2198

**Comment by gnidorah** [comment]
Cool. What do you think about video support? https://github.com/typora/typora-issues/issues/2155
Currently Typora doesn't
1. Copy video to custom folder
2. Updates path in Html5 video code (considering relative path setting)

**Comment by peetteerr** [comment]
Providing an image alignment option may also be help.

**Comment by pidgeon777** [comment]
In my opinion, right-clicking on an image and renaming it, is an essential feature to have in a 2020 (almost 2021) markdown editor...

**Comment by actforjason** [comment]
Rename #2218 is very indispensable.

**Comment by pidgeon777** [comment]
> Rename #2218 is very indispensable. But, there has been no any improvement so far(2021).

I agree. Other editors are already supporting this essential feature.
