### ISSUE TITLE
[Summary] Find & Replace Enhancement

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2824]
When a Search box is opened ( <kbd>CTRL</kbd>+<kbd>F</kbd> or <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> ):
* how many search terms can I put in there?
* if I put "apples" "pears", does it search for apples AND pears in the text, or for apples OR pears?
* if the answer to the previous question is AND, how do I do an OR search? And vice versa.
* can I do fuzzy search?
* can I use regular expressions?
* if a term to be searched is placed between "  ", does that mean anything?

---

- [x] regular expressions search
- [ ] Replace in directory (#2822)
- [x] Show total hit counts (#3404)
- [ ] Include or ignore markups (#3260)
- [ ] Pin Search Panel (#3727)

**Comment by adlwawh** [comment]
Hope regular expression search is support both in local and global search

**Comment by vassudanagunta** [comment]
## Find should ignore markup in WYSIWYG mode #3260

When in WYSIWYG mode, and given the text:

```
`Find` should ignore markup in [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG)
mode.

Some people like Typora's *Hybrid* mode. Some people dream of an editor
with a true *WYSIWYG* mode. Typora could make everyone happy with a
simple `Display markup under cursor` switch (issue #1317). 😉
```

`Find` "WYSIWYG mode" should match two items.

In other words, `Find` should operate on the rendered text, not the underlying "source code".  **This is how nearly all rich text editors work.**

When in *source code mode*, `Find` should continue to behave as it does now: it should search the source code, which of course includes markup.

-----

@abnerlee Please don't make this an "search option" as you mentioned in your comment when you closed #3260. That just adds complexity. Far more simple and intuitive:

- in WYSIWYG mode, `Find` searches the rendered text.

- in source code mode, `Find` searches the source code, which of course includes markup.

**Comment by eiis1000** [comment]
It really would be awesome to have regex search.

**Comment by 0x7969** [comment]
> @abnerlee Please don't make this an "search option" as you mentioned in your comment when you closed #3260. That just adds complexity. Far more simple and intuitive:
> 
>     * in WYSIWYG mode, `Find` searches the rendered text.
> 
>     * in source code mode, `Find` searches the source code, which of course includes markup.

I'd agree here.
