### ISSUE TITLE
Allow config and theme of diagrams

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#374]
on https://bramp.github.io/js-sequence-diagrams/, we can select "hand drawn" theme, but how can we use this effect in markdown file? Thanks

**Comment by gautiermichelin** [comment]
+1

**Comment by zggg** [comment]
+ 1

**Comment by zggg** [comment]
+2

**Comment by looveu** [comment]
+1

**Comment by nordinrahman** [comment]
This is a workaround I found, at least working on my machine.

1. Locate file `frame.js`, eg `C:\Program Files\Typora\resources\app\app\window\frame.js`
2. Open it, and locate for text like this: `g.drawSVG(w.find(".md-diagram-panel-preview")[0],{theme:"simple"});`. Since the file is minimized, the shorten variable might be different, but focus on `{theme:"simple"}`
3. Replace the word `"simple"` with `"hand"`
4. Save the changes, and restart *Typora*.

Here is an example of the result:
<img src="https://user-images.githubusercontent.com/726249/34192573-c990c8a2-e589-11e7-803f-8a2fb8e8be99.png" width="50%" />

It's not really ideal. Preferably, there should be some setting configurable from Typora *preference* dialog.

TQ.

**Comment by mattmccray** [comment]
Or perhaps it should be configurable by theme. (somehow)

**Comment by wangpeibin713** [comment]
after changing theme from simple to hand, the word write in Chinese is hidden. Is there any solution?

**Comment by abnerlee** [comment]
Summary: 

- [ ] [Flowchart] switching the theme of sequence chart from "simple" to "hand" #1532
- [ ] [Mermaid] specify "curve" : "basis" #1632
- [ ] [Mermaid] missing LeftPadding in mermaid gantt #1665

**Comment by jonrzhang** [comment]
@nordinrahman Thanks for your workaround, it works for me.
But I'm a macOS user, so the location has a little bit different, 
`/Applications/Typora.app/Contents/Resources/TypeMark/app/main.js`

**Comment by rickywu** [comment]
@abnerlee  But how can I configure mermaid theme?

**Comment by yijia-zhan** [comment]
@abnerlee Is there still a plan to support mermaid configuration?

**Comment by pzhaonet** [comment]
👍

**Comment by mbjarland** [comment]
+1 for adding the ability to define a mermaid configuration object.

**Comment by abnerlee** [comment]
see https://support.typora.io/Draw-Diagrams-With-Markdown/#mermaid-options
and https://support.typora.io/Draw-Diagrams-With-Markdown/#sequence-diagrams-options

**Comment by abnerlee** [comment]
https://mermaid-js.github.io/mermaid/#/./directives is now supported in v1.4.4
