### ISSUE TITLE
'Milestone' markers of Mermaid gantt chart placed incorrectly 

### ISSUE THREAD

**Issue by mushix64** [typora/typora-issues#5704]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

**Describe the bug**
* In Mermaid gantt chart, milestone markers are rendered out of alignment with their actual position.
  * Looks like a similar case to issue #5092 and #1661(Closed), but as far as testing with a similar markdown, the markers are in different positions.
* Only the marker displayed on the screen is incorrect. Markers in the output file correctly placed in all formats.
  * Compared to the correct placement in the output file, the text is positioned correctly, **only the markers are misaligned**.
* Misalignment is not only left to right, but also up and down.
  * As the number of milestone markers increases, they will overhang the lower section.

**To Reproduce**
1. create a Gantt chart
2. place milestones with desired dates and durations
  * place multiple milestones
  * also create another section and chart below the milestone section
4. the milestones are displayed out of alignment.
5. output the displayed chart to a file and compare it with the screen display.

**Expected behavior**
Milestone markers on screen are placed correctly, as the below reference (https://mermaid.js.org/syntax/gantt.html - milestone section)
> _As you may notice, the exact location of the milestone is determined by the initial date for the milestone and the "duration" of the task this way: initial date+duration/2._

**Screenshots / Screencasts**

* Output file (correct placement)
![gantt chart - output (correct)](https://user-images.githubusercontent.com/131251030/233073199-373e56e8-0bf5-4085-92a1-7efd249537ae.png)

* On screen (wrong placement)
<img width="1208" alt="gantt chart - screenshot (wrong)" src="https://user-images.githubusercontent.com/131251030/233073721-f93ec27c-6d67-4d73-8d68-2e8001702ebc.png">

**Sample Markdown File**
(same as issue #5092 )

```
```mermaid
gantt
dateFormat  YYYY-MM-DD
title All items changes to protect the innocent
excludes weekends

section Deliveries
Receive Cables            : milestone, cables, 2022-03-01, 1h
Receive Things x11    : milestone, recvx11, 2022-03-07, 1d
Receive Things x12    : milestone, recvx12, 2022-03-14, 1d
Receive Things x13    : milestone, recvx13, 2022-03-21, 1d

section Setup Connection
Connect A to B  : ab, after cables, 1d
Connect A to C  : ac, after cables ab, 1d

section Setup C
Move things         : mvwn, 2022-03-01, 1d
Install Recipe : recipe, after mvwn, 5d

section Connection
Connect x11 to C : x11, after recvx11, 1d
Connect x12 to C : x12, after recvx12, 1d
Connect x13 to C : x13, after recvx13, 1d

Run something                       : sth, after x13, 10d
```

**Desktop (please complete the following information):**
 - macOS Ventura 13.3.1

**Typora Version**
 - 1.15.13 (6766)

**Comment by abnerlee** [comment]
Seems fixed in v1.6 already
