### ISSUE TITLE
Copy-paste of task list item and subitems only copies the item

### ISSUE THREAD

**Issue by jpmv27** [typora/typora-issues#6110]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Copy-paste of task list item and sub-items only copies the item

**To Reproduce**
1. Create a task list with items and sub-items (2nd level items)
2. Select an item along with its sub-items
3. Copy (e.g., ^C)
4. Paste elsewhere (e.g., ^V)

**Expected behavior**
The copied item and sub-items are pasted

**Actual behavior**
Only the item is pasted, without the sub-items

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (Version 10.0.19045 Build 19045)

**Typora Version**
e.g: 1.9.5

**Additional context**
N/A

**Comment by jpmv27** [comment]
I just realized that _how_ the selection is done above makes a difference.

This way _works as expected_:
- Place the cursor at the beginning (or end) of the items and sub-items to be copied, hold down the mouse button, and use the mouse to move the cursor to the end (or beginning) of the items

This way _shows the problem_:
- Place the cursor at the beginning of the items and sub-items to be copied, hold down the (left) shift key, and use the down arrow key to select the items

Also, and this may be related, there seems to be something "off" about selecting from a task list using the down arrow key. It seems take two down-arrow presses to go down one line, and you can't go down to the next item from the previous item's last sub-item.
